Repository Team-return/JOBIS-DESIGN-SYSTEM-ANDROID-V2, pull requests merged in 2023-12, with the labels that each got.

#2 🔗 :: (#1) 컬러 파운데이션 정의
  app/build.gradle.kts
  jobisdesignsystemv2/src/main/java/team/returm/jobisdesignsystemv2/foundation/Color.kt
  jobisdesignsystemv2/src/main/java/team/returm/jobisdesignsystemv2/foundation/Theme.kt
Labels: 파운데이션

#5 🔗 :: (#3) 타이포그래피 파운데이션 정의
  app/src/androidTest/java/team/returm/jobisdesignsystemv2/ExampleInstrumentedTest.kt
  app/src/main/java/team/returm/jobisdesignsystemv2/MainActivity.kt
  app/src/test/java/team/returm/jobisdesignsystemv2/ExampleUnitTest.kt
  jobisdesignsystemv2/src/androidTest/java/team/returm/jobisdesignsystemv2/ExampleInstrumentedTest.kt
  jobisdesignsystemv2/src/main/java/team/returm/jobisdesignsystemv2/foundation/JobisColor.kt
  jobisdesignsystemv2/src/main/java/team/returm/jobisdesignsystemv2/foundation/JobisTypography.kt
  jobisdesignsystemv2/src/main/java/team/returm/jobisdesignsystemv2/foundation/Theme.kt
  jobisdesignsystemv2/src/main/java/team/returm/jobisdesignsystemv2/foundation/Type.kt
  jobisdesignsystemv2/src/main/res/font/pretendard_bold.otf
  jobisdesignsystemv2/src/main/res/font/pretendard_medium.otf
  jobisdesignsystemv2/src/main/res/font/pretendard_semi_bold.otf
  jobisdesignsystemv2/src/test/java/team/returm/jobisdesignsystemv2/ExampleUnitTest.kt
Labels: 파운데이션

#7 🔗 :: (#6) jobistext 구현
  jobisdesignsystemv2/src/main/java/team/returm/jobisdesignsystemv2/foundation/JobisColor.kt
  jobisdesignsystemv2/src/main/java/team/returm/jobisdesignsystemv2/foundation/JobisTypography.kt
  jobisdesignsystemv2/src/main/java/team/returm/jobisdesignsystemv2/text/JobisText.kt
Labels: 기능 구현

#9 🔗 :: (#8) 문서화
  jobisdesignsystemv2/src/main/java/team/returm/jobisdesignsystemv2/foundation/JobisColor.kt
  jobisdesignsystemv2/src/main/java/team/returm/jobisdesignsystemv2/foundation/JobisTypography.kt
  jobisdesignsystemv2/src/main/java/team/returm/jobisdesignsystemv2/text/JobisText.kt
Labels: 문서

#15 🔗 :: (#12) 아이콘 추가
  jobisdesignsystemv2/src/main/java/team/returm/jobisdesignsystemv2/foundation/JobisIcon.kt
  jobisdesignsystemv2/src/main/res/drawable/ic_arrow.xml
  jobisdesignsystemv2/src/main/res/drawable/ic_bell.xml
  jobisdesignsystemv2/src/main/res/drawable/ic_bookmark_off.xml
  jobisdesignsystemv2/src/main/res/drawable/ic_bookmark_on.xml
  jobisdesignsystemv2/src/main/res/drawable/ic_box.xml
  jobisdesignsystemv2/src/main/res/drawable/ic_check_circle.xml
  jobisdesignsystemv2/src/main/res/drawable/ic_close.xml
  jobisdesignsystemv2/src/main/res/drawable/ic_code.xml
  jobisdesignsystemv2/src/main/res/drawable/ic_delete.xml
  jobisdesignsystemv2/src/main/res/drawable/ic_error.xml
  jobisdesignsystemv2/src/main/res/drawable/ic_eye_off.xml
  jobisdesignsystemv2/src/main/res/drawable/ic_eye_on.xml
  jobisdesignsystemv2/src/main/res/drawable/ic_filter.xml
  jobisdesignsystemv2/src/main/res/drawable/ic_link.xml
  jobisdesignsystemv2/src/main/res/drawable/ic_lock_reset.xml
  jobisdesignsystemv2/src/main/res/drawable/ic_logout.xml
  jobisdesignsystemv2/src/main/res/drawable/ic_long_arrow.xml
  jobisdesignsystemv2/src/main/res/drawable/ic_meeting_room.xml
  jobisdesignsystemv2/src/main/res/drawable/ic_person_remove.xml
  jobisdesignsystemv2/src/main/res/drawable/ic_plus.xml
  jobisdesignsystemv2/src/main/res/drawable/ic_report.xml
  jobisdesignsystemv2/src/main/res/drawable/ic_search.xml
Labels: 파운데이션

#16 🔗 :: (#4) 컬러 팔레트 정의
  jobisdesignsystemv2/src/main/java/team/returm/jobisdesignsystemv2/foundation/JobisColor.kt
  jobisdesignsystemv2/src/main/java/team/returm/jobisdesignsystemv2/foundation/JobisIcon.kt
  jobisdesignsystemv2/src/main/java/team/returm/jobisdesignsystemv2/foundation/Theme.kt
  jobisdesignsystemv2/src/main/java/team/returm/jobisdesignsystemv2/text/JobisText.kt
Labels: 파운데이션

#17 🔗 :: (#10) 버튼 구현하기
  jobisdesignsystemv2/src/main/java/team/returm/jobisdesignsystemv2/button/ButtonColors.kt
  jobisdesignsystemv2/src/main/java/team/returm/jobisdesignsystemv2/button/JobisButton.kt
  jobisdesignsystemv2/src/main/java/team/returm/jobisdesignsystemv2/button/JobisIconButton.kt
  jobisdesignsystemv2/src/main/res/values/strings.xml
Labels: 기능 구현

#18 🔗 :: (#13) 헤더 구현
  jobisdesignsystemv2/src/main/java/team/returm/jobisdesignsystemv2/appbar/JobisTopAppBar.kt
  jobisdesignsystemv2/src/main/java/team/returm/jobisdesignsystemv2/button/JobisButton.kt
  jobisdesignsystemv2/src/main/java/team/returm/jobisdesignsystemv2/button/JobisIconButton.kt
  jobisdesignsystemv2/src/main/java/team/returm/jobisdesignsystemv2/text/JobisText.kt
  jobisdesignsystemv2/src/main/res/drawable/img_jobis.png
  jobisdesignsystemv2/src/main/res/values/strings.xml
Labels: 기능 구현

#19 🔗 :: (#14) 메뉴 카드 구현
  jobisdesignsystemv2/src/main/java/team/returm/jobisdesignsystemv2/button/JobisButton.kt
  jobisdesignsystemv2/src/main/java/team/returm/jobisdesignsystemv2/button/JobisIconButton.kt
  jobisdesignsystemv2/src/main/java/team/returm/jobisdesignsystemv2/card/JobisCard.kt
  jobisdesignsystemv2/src/main/java/team/returm/jobisdesignsystemv2/utils/Clickable.kt
Labels: 기능 구현

#20 🔗 :: (#11) 텍스트 인풋 구현하기
  jobisdesignsystemv2/src/main/java/team/returm/jobisdesignsystemv2/foundation/JobisIcon.kt
  jobisdesignsystemv2/src/main/java/team/returm/jobisdesignsystemv2/textfield/JobisTextField.kt
  jobisdesignsystemv2/src/main/res/drawable/ic_check_circle.xml
  jobisdesignsystemv2/src/main/res/drawable/ic_error.xml
  jobisdesignsystemv2/src/main/res/drawable/ic_information.xml
  jobisdesignsystemv2/src/main/res/values/strings.xml
Labels: 기능 구현

#23 🔗 :: (#22) 토스트 커스텀
  jobisdesignsystemv2/src/main/java/team/returm/jobisdesignsystemv2/toast/JobisToast.kt
  jobisdesignsystemv2/src/main/res/drawable/bg_toast.xml
  jobisdesignsystemv2/src/main/res/drawable/ic_check_circle.xml
  jobisdesignsystemv2/src/main/res/layout/jobis_toast.xml
Labels: 기능 구현
