Repository Team-return/JOBIS-DESIGN-SYSTEM-ANDROID-V2, pull requests merged in 2024-02, with the labels that each got.

#47 🔗 :: (#46) 버튼 클릭 제한
  jobisdesignsystemv2/src/main/java/team/returm/jobisdesignsystemv2/utils/Clickable.kt
Labels: 기능 구현

#49 🔗 :: (#48) 앱 바 로고 옵션 추가
  jobisdesignsystemv2/src/main/java/team/returm/jobisdesignsystemv2/appbar/JobisTopAppBar.kt
Labels: 리팩토링

#50 🔗 :: (#45) 버튼 패딩 조절
  jobisdesignsystemv2/build.gradle.kts
  jobisdesignsystemv2/src/main/java/team/returm/jobisdesignsystemv2/button/JobisButton.kt
  jobisdesignsystemv2/src/main/java/team/returm/jobisdesignsystemv2/textfield/JobisTextField.kt
  jobisdesignsystemv2/src/main/java/team/returm/jobisdesignsystemv2/utils/Clickable.kt
  jobisdesignsystemv2/src/main/java/team/returm/jobisdesignsystemv2/utils/KeyboardAsState.kt
Labels: 버그, 리팩토링

#51 🔗 :: (#44) small 버튼 패딩 조절
  jobisdesignsystemv2/src/androidTest/java/team/returm/jobisdesignsystemv2/JobisButtonTest.kt
  jobisdesignsystemv2/src/androidTest/java/team/returm/jobisdesignsystemv2/JobisTextFieldTest.kt
  jobisdesignsystemv2/src/androidTest/java/team/returm/jobisdesignsystemv2/JobisTextTest.kt
  jobisdesignsystemv2/src/main/java/team/returm/jobisdesignsystemv2/appbar/JobisTopAppBar.kt
  jobisdesignsystemv2/src/main/java/team/returm/jobisdesignsystemv2/button/JobisButton.kt
  jobisdesignsystemv2/src/main/java/team/returm/jobisdesignsystemv2/foundation/JobisTypography.kt
  jobisdesignsystemv2/src/main/java/team/returm/jobisdesignsystemv2/text/JobisText.kt
  jobisdesignsystemv2/src/main/java/team/returm/jobisdesignsystemv2/textfield/JobisTextField.kt
Labels: 버그, 기능 구현, 리팩토링

#53 🔗 :: (#52) top app bar 아이콘 정렬
  jobisdesignsystemv2/src/main/java/team/returm/jobisdesignsystemv2/appbar/JobisTopAppBar.kt
Labels: 버그
