Repository Team-return/JOBIS-DESIGN-SYSTEM-ANDROID-V2, pull requests merged in 2024-01, with the labels that each got.

#25 🔗 :: (#24) 배포 설정
  jobisdesignsystemv2/build.gradle.kts
  settings.gradle.kts
Labels: 배포

#28 🔀 :: (#27) 버튼 내부 패딩 조절
  jobisdesignsystemv2/src/main/java/team/returm/jobisdesignsystemv2/button/JobisButton.kt
Labels: 버그

#31 🔗 :: (#29) 텍스트 필드 버그
  jobisdesignsystemv2/src/main/java/team/returm/jobisdesignsystemv2/button/JobisIconButton.kt
  jobisdesignsystemv2/src/main/java/team/returm/jobisdesignsystemv2/textfield/JobisTextField.kt
Labels: 버그

#32 🔗 :: (#30) 앱 바 내부 패딩 수정
  jobisdesignsystemv2/src/main/java/team/returm/jobisdesignsystemv2/appbar/JobisTopAppBar.kt
  jobisdesignsystemv2/src/main/java/team/returm/jobisdesignsystemv2/button/JobisIconButton.kt
Labels: 버그

#34 🔗 :: (#33) 1.0.1 배포
  jobisdesignsystemv2/build.gradle.kts
Labels: 배포

#38 🔗 :: (#37) 텍스트 필드 버튼 구현
  jobisdesignsystemv2/src/main/java/team/returm/jobisdesignsystemv2/appbar/JobisTopAppBar.kt
  jobisdesignsystemv2/src/main/java/team/returm/jobisdesignsystemv2/button/ButtonColors.kt
  jobisdesignsystemv2/src/main/java/team/returm/jobisdesignsystemv2/button/JobisButton.kt
  jobisdesignsystemv2/src/main/java/team/returm/jobisdesignsystemv2/textfield/JobisTextField.kt
Labels: 버그, 기능 구현

#40 🔗 :: (#39) 텍스트 필드 키보드 옵션 구현
  jobisdesignsystemv2/src/main/java/team/returm/jobisdesignsystemv2/textfield/JobisTextField.kt
Labels: 기능 구현

#41 🔗 :: v1.1.0
  jobisdesignsystemv2/build.gradle.kts
  jobisdesignsystemv2/src/main/java/team/returm/jobisdesignsystemv2/appbar/JobisTopAppBar.kt
  jobisdesignsystemv2/src/main/java/team/returm/jobisdesignsystemv2/button/ButtonColors.kt
  jobisdesignsystemv2/src/main/java/team/returm/jobisdesignsystemv2/button/JobisButton.kt
  jobisdesignsystemv2/src/main/java/team/returm/jobisdesignsystemv2/textfield/JobisTextField.kt
Labels: 배포

#43 🔗 :: (#42) ui 테스트
  jobisdesignsystemv2/build.gradle.kts
  jobisdesignsystemv2/src/androidTest/java/team/returm/jobisdesignsystemv2/JobisButtonTest.kt
  jobisdesignsystemv2/src/androidTest/java/team/returm/jobisdesignsystemv2/JobisTextFieldTest.kt
  jobisdesignsystemv2/src/androidTest/java/team/returm/jobisdesignsystemv2/JobisTextTest.kt
Labels: 기능 구현
